# Generated by Django 3.2.7 on 2021-10-20 22:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0003_blogpost_author_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogpost',
            options={'ordering': ('-created',)},
        ),
        migrations.RenameField(
            model_name='blogpost',
            old_name='created_on',
            new_name='created',
        ),
        migrations.RenameField(
            model_name='blogpost',
            old_name='post_head',
            new_name='heading',
        ),
        migrations.RenameField(
            model_name='blogpost',
            old_name='post_main',
            new_name='main',
        ),
        migrations.RenameField(
            model_name='blogpost',
            old_name='blog_title',
            new_name='title',
        ),
        migrations.RemoveField(
            model_name='blogpost',
            name='author_id',
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
