# Generated by Django 3.2.7 on 2021-10-20 22:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_alter_blogpost_author'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogpost',
            options={'ordering': ('-blog_created',)},
        ),
        migrations.RenameField(
            model_name='blogpost',
            old_name='author',
            new_name='blog_author',
        ),
        migrations.RenameField(
            model_name='blogpost',
            old_name='created',
            new_name='blog_created',
        ),
        migrations.RenameField(
            model_name='blogpost',
            old_name='email',
            new_name='blog_email',
        ),
        migrations.RenameField(
            model_name='blogpost',
            old_name='heading',
            new_name='blog_heading',
        ),
        migrations.RenameField(
            model_name='blogpost',
            old_name='image',
            new_name='blog_image',
        ),
        migrations.RenameField(
            model_name='blogpost',
            old_name='image_url',
            new_name='blog_image_url',
        ),
        migrations.RenameField(
            model_name='blogpost',
            old_name='main',
            new_name='blog_main',
        ),
        migrations.RenameField(
            model_name='blogpost',
            old_name='slug',
            new_name='blog_slug',
        ),
        migrations.RenameField(
            model_name='blogpost',
            old_name='title',
            new_name='blog_title',
        ),
    ]
