# Generated by Django 3.2.7 on 2021-10-20 23:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_alter_blogpost_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpost',
            name='blog_image',
        ),
        migrations.RemoveField(
            model_name='blogpost',
            name='blog_image_url',
        ),
    ]
