# Generated by Django 3.2.7 on 2021-10-20 23:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20211020_2323'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpost',
            name='blog_author',
        ),
        migrations.RemoveField(
            model_name='blogpost',
            name='blog_created',
        ),
        migrations.RemoveField(
            model_name='blogpost',
            name='blog_email',
        ),
        migrations.RemoveField(
            model_name='blogpost',
            name='blog_heading',
        ),
        migrations.RemoveField(
            model_name='blogpost',
            name='blog_main',
        ),
        migrations.RemoveField(
            model_name='blogpost',
            name='blog_slug',
        ),
    ]
