# Generated by Django 3.2.7 on 2021-10-21 15:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0009_auto_20211020_2325'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='blog_author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blog_post', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='blog_created',
            field=models.DateTimeField(auto_now_add=True, default='default'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='blogpost',
            name='blog_heading',
            field=models.CharField(default='default value', max_length=400),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='blogpost',
            name='blog_image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='blog_image_url',
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='blog_main',
            field=models.TextField(default='default value'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='blogpost',
            name='blog_slug',
            field=models.SlugField(default='default value', max_length=200),
            preserve_default=False,
        ),
    ]
