# Generated by Django 3.2.7 on 2021-10-10 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20211010_1512'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='brand_image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='product',
            name='brand_url',
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
    ]
